import { Provider } from "@/components/ui/provider";
import "./globals.css";
import "@mantine/core/styles.css";
import { Theme } from "@chakra-ui/react";
import "./styles/slick-slider.css";
import "./styles/global.scss";
import { MantineProvider } from "@mantine/core";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MantineProvider>
          <Provider themes={"light"} enableSystem={false}>
            <Theme appearance="light">{children}
              <Toaster position="top-right" />
            </Theme>
          </Provider>
        </MantineProvider>
      </body>
    </html>
  );
}
